//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.QueoFlow.Peanuts.Net.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Web() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.QueoFlow.Peanuts.Net.Web.Resources.Resources_Web", typeof(Resources_Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string _common_element_key {
            get {
                return ResourceManager.GetString("_common_element_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string _viewname_module_element_key {
            get {
                return ResourceManager.GetString("_viewname_module_element_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnung erstellen ähnelt.
        /// </summary>
        public static string bill_btn_create {
            get {
                return ResourceManager.GetString("bill_btn_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string btn_Cancel_Create {
            get {
                return ResourceManager.GetString("btn_Cancel_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen verwerfen ähnelt.
        /// </summary>
        public static string btn_Cancel_Update {
            get {
                return ResourceManager.GetString("btn_Cancel_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string btn_Save_Create {
            get {
                return ResourceManager.GetString("btn_Save_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern &amp; zurück ähnelt.
        /// </summary>
        public static string btn_Save_Update {
            get {
                return ResourceManager.GetString("btn_Save_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Akzeptieren ähnelt.
        /// </summary>
        public static string common_btn_Accept {
            get {
                return ResourceManager.GetString("common_btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string common_btn_Add {
            get {
                return ResourceManager.GetString("common_btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hinzufügen ähnelt.
        /// </summary>
        public static string common_btn_Add_Entity {
            get {
                return ResourceManager.GetString("common_btn_Add_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        public static string common_btn_ChangePassword {
            get {
                return ResourceManager.GetString("common_btn_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string common_btn_Delete {
            get {
                return ResourceManager.GetString("common_btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string common_btn_Edit {
            get {
                return ResourceManager.GetString("common_btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        public static string common_btn_Login {
            get {
                return ResourceManager.GetString("common_btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        public static string common_btn_Logout {
            get {
                return ResourceManager.GetString("common_btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erste Seite ähnelt.
        /// </summary>
        public static string common_btn_PagerFirstPage {
            get {
                return ResourceManager.GetString("common_btn_PagerFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Seite ähnelt.
        /// </summary>
        public static string common_btn_PagerLastPage {
            get {
                return ResourceManager.GetString("common_btn_PagerLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer ähnelt.
        /// </summary>
        public static string common_btn_PagerNewer {
            get {
                return ResourceManager.GetString("common_btn_PagerNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string common_btn_PagerNext {
            get {
                return ResourceManager.GetString("common_btn_PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Älter ähnelt.
        /// </summary>
        public static string common_btn_PagerOlder {
            get {
                return ResourceManager.GetString("common_btn_PagerOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        public static string common_btn_PagerPrevious {
            get {
                return ResourceManager.GetString("common_btn_PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort vergessen ähnelt.
        /// </summary>
        public static string common_btn_PasswordLost {
            get {
                return ResourceManager.GetString("common_btn_PasswordLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        public static string common_btn_Reset {
            get {
                return ResourceManager.GetString("common_btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        public static string common_btn_Search {
            get {
                return ResourceManager.GetString("common_btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeigen ähnelt.
        /// </summary>
        public static string common_btn_Show {
            get {
                return ResourceManager.GetString("common_btn_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übernehmen ähnelt.
        /// </summary>
        public static string common_btn_Submit {
            get {
                return ResourceManager.GetString("common_btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string common_error_Message {
            get {
                return ResourceManager.GetString("common_error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string common_error_Title {
            get {
                return ResourceManager.GetString("common_error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:d} ähnelt.
        /// </summary>
        public static string common_format_Date {
            get {
                return ResourceManager.GetString("common_format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:d} - {1:d} Uhr ähnelt.
        /// </summary>
        public static string common_format_DateRange {
            get {
                return ResourceManager.GetString("common_format_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:g} Uhr ähnelt.
        /// </summary>
        public static string common_format_DateTime {
            get {
                return ResourceManager.GetString("common_format_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:g} - {1:g} Uhr ähnelt.
        /// </summary>
        public static string common_format_DateTimeRange {
            get {
                return ResourceManager.GetString("common_format_DateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:d} {0:t} - {1:t} Uhr ähnelt.
        /// </summary>
        public static string common_format_DateWithTimeRange {
            get {
                return ResourceManager.GetString("common_format_DateWithTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string common_label_NewPassword {
            get {
                return ResourceManager.GetString("common_label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort wiederholen ähnelt.
        /// </summary>
        public static string common_label_NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("common_label_NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        public static string common_label_Options {
            get {
                return ResourceManager.GetString("common_label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite ähnelt.
        /// </summary>
        public static string common_label_Page {
            get {
                return ResourceManager.GetString("common_label_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite {0} ähnelt.
        /// </summary>
        public static string common_label_PageNumber {
            get {
                return ResourceManager.GetString("common_label_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        public static string common_label_Register {
            get {
                return ResourceManager.GetString("common_label_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechtigungen ähnelt.
        /// </summary>
        public static string common_label_Rights {
            get {
                return ResourceManager.GetString("common_label_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nutzer suchen ... ähnelt.
        /// </summary>
        public static string common_label_SearchUsers {
            get {
                return ResourceManager.GetString("common_label_SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen Bestätigen ähnelt.
        /// </summary>
        public static string common_label_SubmitDelete {
            get {
                return ResourceManager.GetString("common_label_SubmitDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte auswählen ähnelt.
        /// </summary>
        public static string common_placeholder_DropDown_Select {
            get {
                return ResourceManager.GetString("common_placeholder_DropDown_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} erstellen ähnelt.
        /// </summary>
        public static string common_title_CreateCommand {
            get {
                return ResourceManager.GetString("common_title_CreateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} löschen: {1} ähnelt.
        /// </summary>
        public static string common_title_DeleteCommand {
            get {
                return ResourceManager.GetString("common_title_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}übersicht ähnelt.
        /// </summary>
        public static string common_title_IndexView {
            get {
                return ResourceManager.GetString("common_title_IndexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mein Profil ähnelt.
        /// </summary>
        public static string common_title_ManageView {
            get {
                return ResourceManager.GetString("common_title_ManageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} beantragen ähnelt.
        /// </summary>
        public static string common_title_ProposeCommand {
            get {
                return ResourceManager.GetString("common_title_ProposeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} bearbeiten: {1} ähnelt.
        /// </summary>
        public static string common_title_UpdateCommand {
            get {
                return ResourceManager.GetString("common_title_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die {0} {1} wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string common_txt_confirm_delete_feminin {
            get {
                return ResourceManager.GetString("common_txt_confirm_delete_feminin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der {0} {1} wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string common_txt_confirm_delete_maskulin {
            get {
                return ResourceManager.GetString("common_txt_confirm_delete_maskulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die am {0:d} Uhr ähnelt.
        /// </summary>
        public static string common_txt_Date {
            get {
                return ResourceManager.GetString("common_txt_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vom {0:d} bis zum {1:d} ähnelt.
        /// </summary>
        public static string common_txt_DateRange {
            get {
                return ResourceManager.GetString("common_txt_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis {0:d} ähnelt.
        /// </summary>
        public static string common_txt_DateRangeEnd {
            get {
                return ResourceManager.GetString("common_txt_DateRangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        public static string common_txt_DateRangeNone {
            get {
                return ResourceManager.GetString("common_txt_DateRangeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ab {0:d} ähnelt.
        /// </summary>
        public static string common_txt_DateRangeStart {
            get {
                return ResourceManager.GetString("common_txt_DateRangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die am {0:d} um {0:t} Uhr ähnelt.
        /// </summary>
        public static string common_txt_DateTime {
            get {
                return ResourceManager.GetString("common_txt_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vom {0:g} Uhr bis zum {1:g} Uhr ähnelt.
        /// </summary>
        public static string common_txt_DateTimeRange {
            get {
                return ResourceManager.GetString("common_txt_DateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis {0:d} {0:t} Uhr ähnelt.
        /// </summary>
        public static string common_txt_DateTimeRangeEnd {
            get {
                return ResourceManager.GetString("common_txt_DateTimeRangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ab {0:d} {0:t} Uhr ähnelt.
        /// </summary>
        public static string common_txt_DateTimeRangeStart {
            get {
                return ResourceManager.GetString("common_txt_DateTimeRangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die am {0:d} von {0:t} bis {1:t} Uhr ähnelt.
        /// </summary>
        public static string common_txt_DateWithTimeRange {
            get {
                return ResourceManager.GetString("common_txt_DateWithTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Aufrufen der Seite fehlen die notwendigen Berechtigung. ähnelt.
        /// </summary>
        public static string error_Forbidden_Message {
            get {
                return ResourceManager.GetString("error_Forbidden_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Berechtigung ähnelt.
        /// </summary>
        public static string error_Forbidden_Title {
            get {
                return ResourceManager.GetString("error_Forbidden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die aufgerufene Seite existiert nicht! ähnelt.
        /// </summary>
        public static string error_NotFound_Message {
            get {
                return ResourceManager.GetString("error_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht gefunden ähnelt.
        /// </summary>
        public static string error_NotFound_Title {
            get {
                return ResourceManager.GetString("error_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Seite ist nur für angemeldete Nutzer aufrufbar. ähnelt.
        /// </summary>
        public static string error_Unauthorized_Message {
            get {
                return ResourceManager.GetString("error_Unauthorized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht angemeldet ähnelt.
        /// </summary>
        public static string error_Unauthorized_Title {
            get {
                return ResourceManager.GetString("error_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler: ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_ErrorList {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mittel ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_Medium {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die normal ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_Normal {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stark ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_Strong {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sehr stark ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_VeryStrong {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sehr schwach ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_VeryWeak {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_VeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die schwach ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_Weak {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort ist zu kurz ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordLength {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort darf die E-Mail Adresse nicht enthalten ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordNotEmail {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu viele Wiederholungen ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordRepetitions {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort enthält Buchstabensequenzen ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordSequences {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort darf den Benutzernamen nicht enthalten ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordSimilarToUsername {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordSimilarToUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sollten Buchstaben und Ziffern verwendet werden ähnelt.
        /// </summary>
        public static string hint_PasswordStrength_WordTwoCharacterClasses {
            get {
                return ResourceManager.GetString("hint_PasswordStrength_WordTwoCharacterClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        public static string label_False {
            get {
                return ResourceManager.GetString("label_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        public static string label_No {
            get {
                return ResourceManager.GetString("label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite {0} von {1} ähnelt.
        /// </summary>
        public static string label_Page_Current_Of_Total {
            get {
                return ResourceManager.GetString("label_Page_Current_Of_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        public static string label_True {
            get {
                return ResourceManager.GetString("label_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        public static string label_Yes {
            get {
                return ResourceManager.GetString("label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zahlung erstellen ähnelt.
        /// </summary>
        public static string payment_btn_create {
            get {
                return ResourceManager.GetString("payment_btn_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peanut erstellen ähnelt.
        /// </summary>
        public static string peanut_btn_create {
            get {
                return ResourceManager.GetString("peanut_btn_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string peanut_requirement_name_placeholder {
            get {
                return ResourceManager.GetString("peanut_requirement_name_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menge ähnelt.
        /// </summary>
        public static string peanut_requirement_quantity_placeholder {
            get {
                return ResourceManager.GetString("peanut_requirement_quantity_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einheit ähnelt.
        /// </summary>
        public static string peanut_requirement_unit_placeholder {
            get {
                return ResourceManager.GetString("peanut_requirement_unit_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL ähnelt.
        /// </summary>
        public static string peanut_requirement_url_placeholder {
            get {
                return ResourceManager.GetString("peanut_requirement_url_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der beantragte Nutzer {0} wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string txt_Confirm_Delete_ProposedUser {
            get {
                return ResourceManager.GetString("txt_Confirm_Delete_ProposedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Nutzer {0} wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string txt_Confirm_Delete_User {
            get {
                return ResourceManager.GetString("txt_Confirm_Delete_User", resourceCulture);
            }
        }
    }
}
